"""
Responsible RAG Auditor — FastAPI Backend
==========================================
The main application entry point. Wires all 5 audit modules together
and exposes them as a clean REST API.

ARCHITECTURE PATTERN — "Middleware Auditor":
  This server does NOT replace your RAG pipeline.
  It sits ALONGSIDE it. You send it the inputs/outputs of your pipeline
  and it tells you what governance risks were found.
  This is called the "sidecar pattern" in microservices architecture —
  a separate service that monitors another service without modifying it.

API ENDPOINTS:
  POST /audit          — Main audit endpoint (runs all 5 modules)
  GET  /history        — Get audit log history
  GET  /audit/{id}     — Get specific audit record
  GET  /health         — Health check
  GET  /               — Serve the HTML frontend

CORS (Cross-Origin Resource Sharing):
  Since our HTML frontend is served from a different origin than the API,
  we enable CORS. This is a browser security mechanism. Without it,
  the browser would block our frontend from calling our API.
  In production: restrict CORS to specific allowed origins.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from typing import List, Optional
import time
from pathlib import Path

# Import our 5 audit modules
from modules.pii_detector import run_pii_check
from modules.groundedness_checker import run_groundedness_check
from modules.bias_flagger import run_bias_check
from modules.prompt_injection_detector import run_injection_check
from modules.audit_logger import log_audit, get_audit_history, get_audit_by_id, initialise_db, clear_audit_history, delete_audit_by_id

# ── App Initialisation ───────────────────────────────────────────────────────

app = FastAPI(
    title="Responsible RAG Auditor",
    description=(
        "A governance and safety auditing tool for RAG (Retrieval Augmented Generation) "
        "pipelines. Checks for PII leakage, hallucination, bias, prompt injection, "
        "and maintains a tamper-evident audit trail. "
        "Maps to: NIST AI RMF, RBI FREE-AI, EU AI Act, DPDP Act 2023."
    ),
    version="1.0.0",
    docs_url="/docs",      # Swagger UI — auto-generated API documentation
    redoc_url="/redoc"     # ReDoc — alternative API documentation view
)

# ── CORS Middleware ──────────────────────────────────────────────────────────
# Allow the HTML frontend (any origin in dev) to call this API.
# In production: replace "*" with your actual frontend URL.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Static File Serving ──────────────────────────────────────────────────────
# Serve the HTML frontend from the /frontend directory
FRONTEND_DIR = Path(__file__).parent.parent / "frontend"


# ── Startup Event ─────────────────────────────────────────────────────────────
@app.on_event("startup")
async def startup_event():
    """Initialise database on server start."""
    initialise_db()
    print("✅ Responsible RAG Auditor started. DB initialised.")
    print("📊 Swagger docs available at: http://localhost:8000/docs")


# ── Request / Response Models (Pydantic) ─────────────────────────────────────
# Pydantic models define the exact shape of data we accept and return.
# This is input validation — a core software engineering best practice.
# If the request doesn't match this shape, FastAPI auto-returns a 422 error.

class AuditRequest(BaseModel):
    """
    The input to the auditor.
    Every RAG pipeline produces exactly these 3 things:
    a query, retrieved chunks, and a generated answer.
    """
    query: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="The original user query sent to the RAG pipeline",
        example="What is Newton's second law of motion?"
    )
    retrieved_chunks: List[str] = Field(
        ...,
        min_items=1,
        max_items=20,
        description="List of text chunks retrieved from the knowledge base",
        example=["Force equals mass times acceleration. F=ma is the mathematical form."]
    )
    generated_answer: str = Field(
        ...,
        min_length=1,
        max_length=10000,
        description="The answer generated by the LLM",
        example="Newton's second law states that force equals mass times acceleration (F=ma)."
    )
    # Optional metadata
    pipeline_name: Optional[str] = Field(
        default="unknown",
        description="Name of the RAG pipeline being audited (e.g., 'Vidya AI', 'FinBot')"
    )
    model_version: Optional[str] = Field(
        default="unknown",
        description="LLM model used (e.g., 'llama-3.3-70b', 'gemini-pro')"
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session identifier for grouping related queries"
    )
    groundedness_threshold: Optional[float] = Field(
        default=0.35,
        ge=0.0, le=1.0,
        description="Cosine similarity threshold for groundedness check (0.0-1.0)"
    )


class AuditResponse(BaseModel):
    """The full audit report returned to the frontend."""
    audit_id: str
    timestamp_utc: str
    overall_status: str
    overall_risk_score: int
    processing_time_ms: float
    modules: dict
    content_hash: str


# ── Main Audit Endpoint ───────────────────────────────────────────────────────

@app.post("/audit", response_model=None)
async def run_audit(request: AuditRequest):
    """
    Main endpoint — runs all 5 audit modules and returns a complete report.

    EXECUTION ORDER matters:
    1. Prompt injection FIRST — if query is malicious, flag immediately
    2. PII check — scan for data privacy issues
    3. Groundedness — evaluate answer quality
    4. Bias check — evaluate fairness
    5. Audit logging LAST — log everything including all module results

    This ordering is itself a governance design decision:
    catching injection early means we don't waste compute on a malicious query.
    """
    start_time = time.time()

    try:
        # ── Module 5: Prompt Injection (run first — security gate) ───────────
        injection_result = run_injection_check(
            query=request.query,
            retrieved_chunks=request.retrieved_chunks,
            generated_answer=request.generated_answer
        )

        # ── Module 1: PII Detection ──────────────────────────────────────────
        pii_result = run_pii_check(
            query=request.query,
            retrieved_chunks=request.retrieved_chunks,
            generated_answer=request.generated_answer
        )

        # ── Module 2: Groundedness Check ─────────────────────────────────────
        groundedness_result = run_groundedness_check(
            query=request.query,
            retrieved_chunks=request.retrieved_chunks,
            generated_answer=request.generated_answer,
            threshold=request.groundedness_threshold
        )

        # ── Module 3: Bias Flagging ──────────────────────────────────────────
        bias_result = run_bias_check(
            query=request.query,
            retrieved_chunks=request.retrieved_chunks,
            generated_answer=request.generated_answer
        )

        # ── Combine all results ───────────────────────────────────────────────
        module_results = {
            "prompt_injection": injection_result,
            "pii": pii_result,
            "groundedness": groundedness_result,
            "bias": bias_result
        }

        # ── Module 4: Audit Logging (always runs, even if others fail) ───────
        audit_result = log_audit(
            query=request.query,
            retrieved_chunks=request.retrieved_chunks,
            generated_answer=request.generated_answer,
            module_results=module_results,
            session_id=request.session_id,
            model_version=request.model_version,
            pipeline_name=request.pipeline_name
        )

        processing_time = (time.time() - start_time) * 1000  # Convert to ms

        # ── Build final response ──────────────────────────────────────────────
        return {
            "audit_id": audit_result["audit_id"],
            "timestamp_utc": audit_result["timestamp_utc"],
            "overall_status": audit_result["overall_status"],
            "overall_risk_score": audit_result["overall_risk_score"],
            "content_hash": audit_result["content_hash"],
            "processing_time_ms": round(processing_time, 2),
            "pipeline_name": request.pipeline_name,
            "model_version": request.model_version,
            "modules": {
                "prompt_injection": injection_result,
                "pii": pii_result,
                "groundedness": groundedness_result,
                "bias": bias_result,
                "audit_trail": audit_result
            }
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Audit failed: {str(e)}. Check server logs."
        )


# ── History Endpoint ──────────────────────────────────────────────────────────

@app.get("/history")
async def get_history(limit: int = 50):
    """Return recent audit records for the dashboard history table."""
    records = get_audit_history(limit=limit)
    return {"records": records, "count": len(records)}


# ── Clear History Endpoint ───────────────────────────────────────────────────

@app.delete("/history")
async def delete_history():
    """
    Delete all audit records.
    Uses HTTP DELETE method — the correct REST verb for deletion.

    REST API DESIGN NOTE (Interview talking point):
    HTTP methods have specific meanings:
    GET    = read data        (safe, no side effects)
    POST   = create data      (used for /audit)
    DELETE = delete data      (used here)
    PUT    = replace data
    PATCH  = partially update

    Using the correct HTTP verb is called 'RESTful design'.
    A common mistake is using POST for everything — wrong practice.
    """
    result = clear_audit_history()
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result["message"])
    return result


# ── Single Record Endpoint ────────────────────────────────────────────────────

@app.get("/audit/{audit_id}")
async def get_audit_record(audit_id: str):
    """Return a specific audit record by ID — for drill-down view."""
    record = get_audit_by_id(audit_id)
    if not record:
        raise HTTPException(status_code=404, detail=f"Audit record {audit_id} not found.")
    return record


@app.delete("/audit/{audit_id}")
async def delete_audit_record(audit_id: str):
    """
    Delete a single audit record by ID.
    Uses HTTP DELETE with a path parameter — standard RESTful design.

    PATH PARAMETER vs QUERY PARAMETER (Interview note):
    /audit/{audit_id}  → path parameter  → identifies a specific resource
    /audit?id=xxx      → query parameter → used for filtering/searching
    REST convention: use path params to identify resources, query params to filter.
    """
    result = delete_audit_by_id(audit_id)
    if not result["success"]:
        raise HTTPException(status_code=404, detail=result["message"])
    return result


# ── Health Check ──────────────────────────────────────────────────────────────

@app.get("/health")
async def health_check():
    """
    Health check endpoint — standard in production APIs.
    Load balancers and monitoring tools ping this to check if the service is up.
    """
    return {
        "status": "healthy",
        "service": "Responsible RAG Auditor",
        "version": "1.0.0",
        "modules": [
            "PII Detection",
            "Groundedness Check",
            "Bias Flagging",
            "Audit Trail",
            "Prompt Injection Detection"
        ]
    }


# ── Frontend Serving ──────────────────────────────────────────────────────────

@app.get("/")
async def serve_frontend():
    """Serve the HTML frontend dashboard."""
    index_path = FRONTEND_DIR / "index.html"
    if index_path.exists():
        return FileResponse(str(index_path))
    return {"message": "Frontend not found. Place index.html in /frontend directory."}


# ── Run ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True  # Auto-restart on code changes (dev mode only)
    )